[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-parse = "0.2.18"
colored = "2.1.0"
counter = "0.6.0"
itertools = "0.13.0"
rational = "1.6.0"
#num = "0.4.3"
#rayon = "1.10.0"
